version: '3.8'

networks:
  card-game-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

services:
  nats-broker:
    image: nats:latest
    command: --port 4222 --http_port 8222
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      card-game-network:
        ipv4_address: 172.20.0.10

  game-server-1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - SERVER_ID=server-1
      - HTTP_PORT=8080
      - RAFT_PORT=7000
      - NATS_PORT=4222
      - IS_BOOTSTRAP=true
      - KNOWN_PEERS=172.20.0.12:8080:7000,172.20.0.13:8080:7000
      - CLUSTER_NAME=card-game-cluster
    ports:
      - "8081:8080"
      - "7001:7000"
    networks:
      card-game-network:
        ipv4_address: 172.20.0.11
    depends_on:
      - nats-broker

  game-server-2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - SERVER_ID=server-2
      - HTTP_PORT=8080
      - RAFT_PORT=7000
      - NATS_PORT=4222
      - IS_BOOTSTRAP=false
      - KNOWN_PEERS=172.20.0.11:8080:7000,172.20.0.13:8080:7000
      - CLUSTER_NAME=card-game-cluster
    ports:
      - "8082:8080"
      - "7002:7000"
    networks:
      card-game-network:
        ipv4_address: 172.20.0.12
    depends_on:
      - nats-broker

  game-server-3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - SERVER_ID=server-3
      - HTTP_PORT=8080
      - RAFT_PORT=7000
      - NATS_PORT=4222
      - IS_BOOTSTRAP=false
      - KNOWN_PEERS=172.20.0.11:8080:7000,172.20.0.12:8080:7000
      - CLUSTER_NAME=card-game-cluster
    ports:
      - "8083:8080"
      - "7003:7000"
    networks:
      card-game-network:
        ipv4_address: 172.20.0.13
    depends_on:
      - nats-broker
